imagePullSecrets: [{ name: ghcr }]
title: Raasch Labs
description: Directory of apps running on this platform.
extraHosts: [raaschlabs.com]
rbac: { readIngresses: true }
listed: false
image: ghcr.io/peterjraasch/www:8100ba55a402afab2a1a2dbd0d0d5374bfeef24e
