apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: { app: {{ .Release.Name }} }
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: { app: {{ .Release.Name }} }
  template:
    metadata:
      labels: { app: {{ .Release.Name }} }
    spec:
      {{- if .Values.rbac.readIngresses }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          env: {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.probes }}
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: {{ .Values.port }} }
            initialDelaySeconds: 20
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: {{ .Values.port }} }
            initialDelaySeconds: 60
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
