apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/peterjraasch/RaaschLabs.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/peterjraasch/RaaschLabs.git
        targetRevision: main
        path: charts/spring-app
        helm:
          releaseName: '{{.path.basename}}'
          valueFiles:
            - '../../apps/{{.path.basename}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true]
